using Rca.Physical.Dimensions.Arithmetric;

namespace Rca.Physical.Tests
{
	/// <summary>
	/// THIS CLASS IS AUTO GENERATED!
	/// ALL CHANGES ARE OVERWRITTEN BY EXECUTION OF THE Rca.Physics.Io PROJECT
	/// </summary>
	public class AutoGenerated
	{
		internal static FunctionDescription[] DerivativeFunctions = new FunctionDescription[]
		{
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Force, PhysicalDimensions.Mass, PhysicalDimensions.Acceleration),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Time, PhysicalDimensions.Energy, PhysicalDimensions.Action),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Energy, PhysicalDimensions.Time, PhysicalDimensions.Action),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Length, PhysicalDimensions.Length, PhysicalDimensions.Area),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Volume, PhysicalDimensions.Length, PhysicalDimensions.Area),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.HeatFluxDestiny, PhysicalDimensions.Area),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.VolumetricFlowRate, PhysicalDimensions.Speed, PhysicalDimensions.Area),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.CostsPerTime, PhysicalDimensions.Time, PhysicalDimensions.Costs),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Time, PhysicalDimensions.Costs, PhysicalDimensions.CostsPerTime),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Costs, PhysicalDimensions.Time, PhysicalDimensions.CostsPerTime),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Mass, PhysicalDimensions.Volume, PhysicalDimensions.Destiny),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Time, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.ElectricCharge),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.Time, PhysicalDimensions.ElectricCharge),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Power, PhysicalDimensions.Voltage, PhysicalDimensions.ElectricCurrent),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.ElectricCharge, PhysicalDimensions.Time, PhysicalDimensions.ElectricCurrent),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Time, PhysicalDimensions.Power, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Length, PhysicalDimensions.Force, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.ThermodynamicTemperature, PhysicalDimensions.Entropy, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Power, PhysicalDimensions.Time, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Area, PhysicalDimensions.HeatFluxDestiny, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Force, PhysicalDimensions.Length, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Action, PhysicalDimensions.Time, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Entropy, PhysicalDimensions.ThermodynamicTemperature, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.HeatFluxDestiny, PhysicalDimensions.Area, PhysicalDimensions.Energy),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.ThermodynamicTemperature, PhysicalDimensions.Entropy),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Mass, PhysicalDimensions.Acceleration, PhysicalDimensions.Force),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Length, PhysicalDimensions.Force),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Acceleration, PhysicalDimensions.Mass, PhysicalDimensions.Force),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Area, PhysicalDimensions.HeatFluxDestiny),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Time, PhysicalDimensions.Speed, PhysicalDimensions.Length),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Area, PhysicalDimensions.Length, PhysicalDimensions.Length),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Volume, PhysicalDimensions.Area, PhysicalDimensions.Length),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Speed, PhysicalDimensions.Time, PhysicalDimensions.Length),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Force, PhysicalDimensions.Length),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Volume, PhysicalDimensions.Destiny, PhysicalDimensions.Mass),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Force, PhysicalDimensions.Acceleration, PhysicalDimensions.Mass),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Destiny, PhysicalDimensions.Volume, PhysicalDimensions.Mass),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.Voltage, PhysicalDimensions.Power),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Voltage, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.Power),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Time, PhysicalDimensions.Power),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Length, PhysicalDimensions.Time, PhysicalDimensions.Speed),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.VolumetricFlowRate, PhysicalDimensions.Area, PhysicalDimensions.Speed),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Entropy, PhysicalDimensions.ThermodynamicTemperature),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Length, PhysicalDimensions.Speed, PhysicalDimensions.Time),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Energy, PhysicalDimensions.Power, PhysicalDimensions.Time),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Action, PhysicalDimensions.Energy, PhysicalDimensions.Time),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.ElectricCharge, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.Time),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.CostsPerTime, PhysicalDimensions.Costs, PhysicalDimensions.Time),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Power, PhysicalDimensions.ElectricCurrent, PhysicalDimensions.Voltage),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Length, PhysicalDimensions.Area, PhysicalDimensions.Volume),
			new FunctionDescription(ArithmetricOperations.Division, PhysicalDimensions.Mass, PhysicalDimensions.Destiny, PhysicalDimensions.Volume),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Area, PhysicalDimensions.Length, PhysicalDimensions.Volume),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Area, PhysicalDimensions.Speed, PhysicalDimensions.VolumetricFlowRate),
			new FunctionDescription(ArithmetricOperations.Multiplication, PhysicalDimensions.Speed, PhysicalDimensions.Area, PhysicalDimensions.VolumetricFlowRate),
		};
	}
}
