
using Rca.Physical.Io;

var controller = new Controller();
Console.WriteLine("ExportUnitsAsCsv");
Console.WriteLine(controller.ExportUnitsAsCsv("..\\..\\..\\..\\SupportedUnits.csv") + " units write in SupportedUnits.csv");
Console.WriteLine();
Console.WriteLine("ExportDerivativeFunctions");
Console.WriteLine(controller.ExportDerivativeFunctions("..\\..\\..\\..\\DerivativeFunctions.csv") + " functions write in DerivativeFunctions.csv");
Console.WriteLine();
Console.WriteLine("GenerateHelperClasses");
Console.WriteLine("Generate " + controller.GenerateHelperClasses("..\\..\\..\\..\\Rca.Physical\\Helpers") + " helper classes in Rca.Physical\\Helpers");

#if DEBUG
Console.WriteLine();
Console.WriteLine("ExportDerivativeFunctionArray");
Console.WriteLine(controller.ExportDerivativeFunctionArray("..\\..\\..\\..\\Rca.Physical.Tests\\AutoGenerated.cs") + " functions write in Rca.Physical.Tests\\AutoGenerated.cs");
#endif
