using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Rca.Physical.Io
{
    class Program
    {
        static Controller controller;

        static void Main(string[] args)
        {
            controller = new Controller();

            controller.ExportUnitsAsCsv("..\\..\\..\\..\\SupportedUnits.csv");
            controller.ExportDerivativeFunctions("..\\..\\..\\..\\DerivativeFunctions.csv");

#if DEBUG
            controller.ExportDerivativeFunctionArray("..\\..\\..\\..\\Rca.Physical.Tests\\AutoGenerated.cs");
#endif
        }
    }
}
