
using Rca.Physical;
using Rca.Physical.Io;
using System.Reflection;


var controller = new Controller();
Console.WriteLine(typeof(Program).Assembly.GetName().FullName);
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine(controller.GetRcaPhysicalInfo());
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Generate SupportedUnits.csv from Rca.Physical.PhysicalUnits");
Console.ForegroundColor= ConsoleColor.Red;
Console.WriteLine(controller.ExportUnitsAsCsv("..\\..\\..\\..\\SupportedUnits.csv") + " units write in SupportedUnits.csv");
Console.ResetColor();
Console.WriteLine();

Console.WriteLine("Generate DerivativeFunctions.csv from Rca.Physical.Calculator");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine(controller.ExportDerivativeFunctions("..\\..\\..\\..\\DerivativeFunctions.csv") + " functions write in DerivativeFunctions.csv");
Console.ResetColor();
Console.WriteLine();

Console.WriteLine("Generate helper classes in Rca.Physical.Helpers from Rca.Physical.PhysicalDimensions");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Generate " + controller.GenerateHelperClasses("..\\..\\..\\..\\Rca.Physical\\Helpers") + " helper classes in Rca.Physical.Helpers");
Console.ResetColor();
Console.WriteLine();

Console.WriteLine("Generate extension class in Rca.Physical from Rca.Physical.PhysicalDimensions");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine("Generate " + controller.GeneratePhysicalUnitExtensions("..\\..\\..\\..\\Rca.Physical") + " extensions in class in Rca.Physical.PhysicalValueExtensions");
Console.ResetColor();
Console.WriteLine();

#if DEBUG
Console.WriteLine();
Console.ForegroundColor = ConsoleColor.Magenta;
Console.WriteLine("The following step is executed only in the DEBUG configuration!");
Console.ResetColor();
Console.WriteLine();
Console.WriteLine("Generate Rca.Physical.Tests\\AutoGenerated.cs from Rca.Physical.Calculator");
Console.ForegroundColor = ConsoleColor.Red;
Console.WriteLine(controller.ExportDerivativeFunctionArray("..\\..\\..\\..\\Rca.Physical.Tests\\AutoGenerated.cs") + " functions write in Rca.Physical.Tests.AutoGenerated.cs");
Console.ResetColor();
Console.WriteLine();
#endif